# .golangci.yml
run:
  timeout: 5m
  issues-exit-code: 1
  skip-dirs:
    - vendor
    - .git


linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
  gosimple:
    go: 1.18
  govet:
    check-shadowing: true
  ineffassign:
    assign: true
  staticcheck:
    checks: ["all"]
  unused:
    check-exported: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true