version: '3.3'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/go-demo-app:latest
    container_name: go-demo-app
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./app.db:/app/app.db:delegated
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 400M
    # App version is handled through the Dockerfile build args