version: '3.3'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/go-demo-app:latest
    container_name: go-demo-app
    restart: always
    ports:
      - '8080:8080'
    # App version is handled through the Dockerfile build args